unfoldadmin/django-unfold

src/unfold/forms.py, src/unfold/sites.py, src/unfold/templates/registration/password_change_done.html, src/unfold/templates/registration/password_change_form.html
Reused `change_password.html` template for own password change template.
Before:
After:
=> Added styling for own password change form

src/unfold/admin.py, src/unfold/templates/admin/change_form.html
This patch will enable usage of attrs parameter used in `decorators.action` decorator to insert custom HTML attributes
=> Add option to insert HTML attributes inside actions detail <a/> tag

src/unfold/admin.py
Currently fields of type GenericIPAddress have no style applied to them. This PR overrides adds them to the FORMFIELD_OVERRIDES so that the necessary classes are applied to them.
=> Override widget for GenericIPAddress fields

pyproject.toml
Tried to use it as described on README.md https://github.com/unfoldadmin/django-unfold#unfold-development but was getting an error.
Using poetry 1.5.1
=> fix: poetry error when used as a local dependency

src/unfold/templatetags/unfold.py
Fixed simple tag "tab_list" if the behavior is overwritten by other packages
```
TypeError at /admin/<application>/<model>/add/
'NoneType' object is not iterable
```
=> Add compatibility if "tab_list" is missing

README.md
=> docs: components sample code typo

src/unfold/contrib/filters/apps.py, src/unfold/contrib/forms/apps.py, src/unfold/contrib/guardian/apps.py, src/unfold/contrib/import_export/apps.py
Add label to contrib apps, to avoid conflicts with `django.forms`
=> fix: put label for all contrib apps

README.md
Hi there,
I noticed an omission in the `django_celery_beat` instructions.
It leads the copy/paste enthusiasts like me to an error where `ClockedSchedule` is unregistered
I figured I'd make a PR to fix it !
Thanks for this project, it's really cool. Keep it up ! 💯
=> docs: missing ClockedSchedule register

src/unfold/templates/unfold/widgets/clearable_file_input.html, src/unfold/templates/unfold/widgets/clearable_file_input_small.html
See: #581
Fixed code:
```html
<div class="flex flex-none items-center leading-none self-stretch">
<div class="hidden">
<input type="file" name="image"  accept="image/*" id="id_image" />
</div>
<label for="id_image" class="cursor-pointer text-gray-400 px-3 hover:text-gray-700 dark:text-gray-500 dark:hover:text-gray-200">
<span class="material-symbols-outlined">upload</span>
</label>
</div>
```
=> fix: double attribute "id" for file field

README.md
Took me a while to figure out what is used for Charts since there was no reference.
I've added the info to the README.md in this PR.
=> docs: add Chart.js credits

README.md
need to add `from django.contrib.auth.models import Group`
=> docs: missing group import

src/unfold/templates/unfold/helpers/tab_list.html, src/unfold/templates/unfold/layouts/skeleton.html
Fixes #570
Hey there,
First, thank you for django-unfold, I love it and I'm pretty sure I'm not alone.
Saving the `activeTab` state would benefit the users IMO: 
Refreshing the page, sharing a link, navigating back and forth would be possible without losing the tab state.
In this PR:
* Save the `activeTab` state in the URL when clicking tabs
* Initialize the `activeTab` variable from the URL during a full reload
There's one problem with my current approach : 
If any hash is detected in the URL, it will become the `activeTab` value. If the hash doesn't match with any tab href, there will be no tab displayed. Maybe to fix this we should have a naming convention for tabs ? Let me know what you think !
Cheers
=> feat: tabs with URL navigation

docs/components/cohort.md
the path for the `cohort.html` in the documentation was wrong,  I have just fixed it.
=> docs: cohort correct file path

src/unfold/contrib/filters/admin.py
Same format as in HTML templates and their {blocktranslate}'s so one msgid may fit them both.
=> chore: filters label formatting

docs/dashboard/index.md
Added templated directory setup instructions before creating `templates/admin/index.html` for the custom dashboard
=> docs: dashboard TEAMPLATES configuration

docs/actions/changelist.md
Current changelist action example has permissions array set as one of method arguments, instead of being passed to `@action` decorator.
=> docs: changelist action permission usage in docs

src/unfold/contrib/simple_history/templates/simple_history/object_history.html, src/unfold/contrib/simple_history/templates/simple_history/object_history_list.html
django-simple-history 3.8.0 introduced pagination for the object history listing.
This is a proposed attempt of a fix for #1036.
It should be noted this will only work with django-simple-history >= 3.8.0.
If support for older versions needs to be retained, more thought needs to be put into this.
=> feat: Add pagination support for simple_history integration

src/unfold/templates/admin/filter.html
Small styling fix for horizontal choice/boolean filters by removing horizontal padding. 
Example before:
Example after:
=> fix: remove horizontal padding for horizontal filter options

src/unfold/contrib/filters/admin/dropdown_filters.py, src/unfold/contrib/filters/admin/mixins.py, src/unfold/contrib/filters/admin/text_filters.py, src/unfold/contrib/filters/templates/unfold/filters/filters_numeric_slider.html
Use consistent/same string already translated in Django for filter labels in all places. 
Here it was already ok: https://github.com/unfoldadmin/django-unfold/blob/1494b95756178a02f1f143411515438df3bddfcc/src/unfold/templates/admin/filter.html#L5
Fix: https://github.com/unfoldadmin/django-unfold/issues/1088
=> fix: use the same translation for all "By {filter_title}"

poetry.lock, pyproject.toml, src/unfold/utils.py, tests/test_utils.py
This uses `str(value)` to display `django-money` value in `display_for_field` and `display_for_value`. Preview follows
I'm unsure if `display_for_value` is needed.
`en`
`de`
Fixes: #942
=> Add support for django-money in display_for_field. Fixes: #942

src/unfold/templates/admin/auth/user/add_form.html
=> fix: typo on user creation popup form

src/unfold/templates/unfold/helpers/messages/errornote.html
Fix missing pluralization in form error message translation
When displaying form errors, Unfold's error message ("Please correct the error below.") is not translated correctly, while Django’s built-in admin properly handles localization via pluralization.
This happens because Django admin uses `{% blocktranslate %}` (pluralization), but Unfold uses separate `{% translate %}` calls for singular and plural, causing mismatches with Django's official translation entries.
Replace separate `{% translate %}` calls with Django’s `{% blocktranslate %}` syntax, matching Django's official admin template.
- Resolves translation mismatch
- Enables pluralization support consistent with Django’s official translations
=> Fix missing pluralization in form error message translation

src/unfold/templates/unfold/helpers/edit_inline/tabular_heading.html
Since the `help_text` is just showing as `title` when you mouseover, `cursor-help` is more expected. With `cursor-pointer` one would expect that you can click on it.
Reference:
- https://v3.tailwindcss.com/docs/cursor
=> ui(tabular_heading): change cursor-pointer to cursor-help

src/unfold/contrib/simple_history/templates/simple_history/submit_line.html
The "Revert" and "Change History" buttons in historical records are not able to be clicked. This is how I modified unfold/contrib/simple_history/templates/submit_line.html to fix it on my end. It is a relatively simple fix and I figured others could benefit from it.
I also added the _cursor-pointer_ css class so that it indicates to the user it can be pressed when hovering over it.
Closes #1375
=> fix simple_history buttons

src/unfold/contrib/import_export/templates/admin/import_export/change_list_import.html
=> fix: add missing template override for django-import-export

src/unfold/templates/unfold/helpers/help_text.html
To align behavior with Django, the `help_text` should not be HTML escaped ([docs](https://docs.djangoproject.com/en/5.2/ref/models/fields/#django.db.models.Field.help_text)).
Fixes: #1263
=> Do not escape HTML in help_text. Fixes: #1263

src/unfold/mixins/base_model_admin.py
See #1483.
The model arg is the class, not an instance of it. 
I can see this removes the type checking error from the [`user_model_admin` fixture](https://github.com/unfoldadmin/django-unfold/blob/main/tests/fixtures.py#L54).
where e.g. with pyright I was previously seeing:
```
Argument of type "type[AbstractUser]" cannot be assigned to parameter "model" of type "Model" in function "__init__"
Type "type[AbstractUser]" is not assignable to type 
```
=> fix: type hint on model in BaseModelAdminMixin.__init__

src/unfold/contrib/constance/templates/admin/constance/change_list.html, src/unfold/contrib/constance/templates/admin/constance/includes/results_list.html
Fixes #1521 
This PR fixes the bug where the Constance admin layout broke when only
CONSTANCE_CONFIG was configured. Missing template tags were added so
both CONSTANCE_CONFIG and CONSTANCE_CONFIG_FIELDSETS render correctly.
=> fix: template layout without constance config

docs/configuration/command.md
Added comma, when directly copying it was breaking.
=> docs: command dict syntax
